### ISSUE TITLE
Floating window doesn't carry over when changing work spaces

### ISSUE THREAD

**Issue by darvid7** [GoogleChromeLabs/picture-in-picture-chrome-extension#21]
Hey!
Thanks for this awesome extension :D 
I've been using it for a few months now and just realized today that the floating window does not carry over when I change work spaces anymore.
I remember previously swapping work spaces would take the floating window with it. 
I'm using a linux desktop.
Thanks!
David :)

**Comment by beaufortfrancois** [comment]
Is your issue similar to https://bugs.chromium.org/p/chromium/issues/detail?id=913630?
If so, it should be fixed in Chrome 74 according to https://chromiumdash.appspot.com/commit/a794e420a57b20359b1ef6cbf76e6d74ef352153

**Comment by mrapogee** [comment]
@beaufortfrancois I don't think that's related. 

I have the same issue on macOS, honestly suprised that this isn't already working because it makes the picture in picture pretty much useless when using full screen apps or multiple desktops. Safari / macOS keeps the PNP window on the display no matter which desktop you transition to.

**Comment by beaufortfrancois** [comment]
I've filed https://bugs.chromium.org/p/chromium/issues/detail?id=954470 to track this issue. Thank you @mrapogee for reporting this issue! I'll have a look.
